commandsAdmin = {
    adminDuty = { commandName = 'adminduty', description = 'Entra de serviço staff [1]' },
    noclip = { commandName = 'nc', description = 'Entra no modo noClip. [1]' },
    sethealth = { commandName = 'setvida', description = 'Seta a vida do jogador.' },
    setarmor = { commandName = 'setcolete', description = 'Seta o colete do jogador.' },
    setadmin = { commandName = 'setadmin', description = 'Seta o nivel do admin.' },
    setmoney = { commandName = 'setmoney', description = 'Enviar dinheiro para um jogador especifico.' },
    banPlayer = { commandName = 'gban', description = 'Bani o jogador do servidor.' },
    kickPlayer = { commandName = 'gkick', description = 'Expulsa o jogador do servidor.' },
    punirPlayer = { commandName = 'gpunir', description = 'Puni um jogador especifico.'},
    unpunirPlayer = { commandName = 'unpunir', description = 'Libera o jogador da punição.' },
    warpPlayer = { commandName = 'tpto', description = 'Telentrasporta para um jogador especifico.' },
    warpPlayerTo = { commandName = 'tptoplayer', description = 'Telentrasporta o jogador para um jogador especifico.' },
    warpPlayerToMe = { commandName = 'tptome', description = 'Telentrasporta o jogador para si mesmo.' },
    godPlayer = { commandName = 'god', description = 'Seta vida e colete 100%' },
    verinv = { commandName = 'verinv', description = 'Mostra o inventario de um jogador especifico.' },
    giveitem = { commandName = 'giveitem', description = 'Envia um item para um jogador especifico.' },
    createvehicle = { commandName = 'car', description = 'Cria um veículo para quem usa o comando.' },
    fixVehicle = { commandName = 'fixar', description = 'Repara o veículo mais próximo ou para um veículo especifico.' },
    destroyvehicle = { commandName = 'dv', description = 'Destroi o carro mais proximo.' },
    infosvehicle = { commandName = 'infoc', description = 'Checa as informações de um veiculo.' },
    namevehicle = { commandName = 'vlist', description = 'Mostrar os nomes de veiculos disponiveis.' },
    createTrash = { commandName = 'clixeira', description = 'Cria uma lixeira na posição do jogador que utilizar o comando.' },
    deleteTrash = { commandName = 'dlixeira', description = 'Deleta a lixeira mais proxima do jogador que utilizar o comando.' }
}

vehicleNames = {"Landstalker", "Bravura", "Buffalo", "Linerunner", "Perennial", "Sentinel", "Dumper", "Fire Truck", "Trashmaster", "Stretch", "Manana", 
                       "Infernus", "Voodoo", "Pony", "Mule", "Cheetah", "Ambulance", "Leviathan", "Moonbeam", "Esperanto", "Taxi", "Washington", "Bobcat", 
                       "Mr. Whoopee", "BF Injection", "Hunter", "Premier", "Enforcer", "Securicar", "Banshee", "Predator", "Bus", "Rhino", "Barracks", "Hotknife", 
                       "Trailer 1", "Previon", "Coach", "Cabbie", "Stallion", "Rumpo", "RC Bandit", "Romero", "Packer", "Monster", "Admiral", "Squalo", 
                       "Seasparrow", "Pizzaboy", "Tram", "Trailer 2", "Turismo", "Speeder", "Reefer", "Tropic", "Flatbed", "Yankee", "Caddy", "Solair", 
                       "Berkley's RC Van", "Skimmer", "PCJ-600", "Faggio", "Freeway", "RC Baron", "RC Raider", "Glendale", "Oceanic", "Sanchez", "Sparrow", "Patriot", 
                       "Quadbike", "Coastguard", "Dinghy", "Hermes", "Sabre", "Rustler", "ZR-350", "Walton", "Regina", "Comet", "BMX", "Burrito", "Camper", "Marquis", 
                       "Baggage", "Dozer", "Maverick", "News Chopper", "Rancher", "FBI Rancher", "Virgo", "Greenwood", "Jetmax", "Hotring Racer", "Sandking", 
                       "Blista Compact", "Police Maverick", "Boxville", "Benson", "Mesa", "RC Goblin", "Hotring Racer 3", "Hotring Racer 2", "Bloodring Banger", 
                       "Rancher Lure", "Super GT", "Elegant", "Journey", "Bike", "Mountain Bike", "Beagle", "Cropduster", "Stuntplane", "Tanker", "Roadtrain", "Nebula", 
                       "Majestic", "Buccaneer", "Shamal", "Hydra", "FCR-900", "NRG-500", "HPV1000", "Cement Truck", "Towtruck", "Fortune", "Cadrona", "FBI Truck", 
                       "Willard", "Forklift", "Tractor", "Combine Harvester", "Feltzer", "Remington", "Slamvan", "Blade", "Freight", "Streak", "Vortex", "Vincent", 
                       "Bullet", "Clover", "Sadler", "Fire Truck Ladder", "Hustler", "Intruder", "Primo", "Cargobob", "Tampa", "Sunrise", "Merit", "Utility Van", 
                       "Nevada", "Yosemite", "Windsor", "Monster 2", "Monster 3", "Uranus", "Jester", "Sultan", "Stratum", "Elegy", "Raindance", "RC Tiger", "Flash", 
                       "Tahoma", "Savanna", "Bandito", "Freight Train Flatbed", "Streak Train Trailer", "Kart", "Mower", "Dune", "Sweeper", "Broadway", "Tornado", 
                       "AT-400", "DFT-30", "Huntley", "Stafford", "BF-400", "Newsvan", "Tug", "Trailer (Tanker Commando)", "Emperor", "Wayfarer", "Euros", "Hotdog", 
                       "Club", "Box Freight", "Trailer 3", "Andromada", "Dodo", "RC Cam", "Launch", "Police LS", "Police", "Police SF", "Police LV", "Police Ranger", 
                       "Ranger", "Picador", "S.W.A.T.", "Alpha", "Phoenix", "Glendale Damaged", "Sadler", "Sadler Damaged", "Baggage Trailer (covered)", 
                       "Baggage Trailer (Uncovered)", "Trailer (Stairs)", "Boxville Mission", "Farm Trailer", "Street Clean Trailer"
}